image: "python:3.7"

before_script:
  - python --version
  - pip install pipenv
  - pipenv lock --requirements > requirements.txt
  - pip install -r requirements.txt

stages:
  - Test

unittest:
  stage: Test
  script:
  - coverage run -m unittest discover
  - coverage report -m
  - coverage-badge
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

