image: "python:3.7"

before_script:
  - python --version
  - pip install pipenv
  - pipenv lock --requirements > requirements.txt
  - pip install -r requirements.txt

stages:
  - Test

unittest:
  stage: Test
  script:
  - python -m unittest discover